###############################################################################
# FMC-HPC, 8 gigabit transceiver enabled, LA & HA user data enabled(HB unused)
###############################################################################

# gigabit clocks
set_property PACKAGE_PIN M6 [get_ports {fmc_hpc_GBTCLK_M2C_N_0}]
set_property PACKAGE_PIN M7 [get_ports {fmc_hpc_GBTCLK_M2C_P_0}]
set_property PACKAGE_PIN H6 [get_ports {fmc_hpc_GBTCLK_M2C_N_1}]
set_property PACKAGE_PIN H7 [get_ports {fmc_hpc_GBTCLK_M2C_P_1}]

set_property PACKAGE_PIN M2 [get_ports {fmc_hpc_DP_M2C_P[0]}]
set_property PACKAGE_PIN M1 [get_ports {fmc_hpc_DP_M2C_N[0]}]
set_property PACKAGE_PIN K2 [get_ports {fmc_hpc_DP_M2C_P[1]}]
set_property PACKAGE_PIN K1 [get_ports {fmc_hpc_DP_M2C_N[1]}]
set_property PACKAGE_PIN H2 [get_ports {fmc_hpc_DP_M2C_P[2]}]
set_property PACKAGE_PIN H1 [get_ports {fmc_hpc_DP_M2C_N[2]}]
set_property PACKAGE_PIN F2 [get_ports {fmc_hpc_DP_M2C_P[3]}]
set_property PACKAGE_PIN F1 [get_ports {fmc_hpc_DP_M2C_N[3]}]
set_property PACKAGE_PIN D2 [get_ports {fmc_hpc_DP_M2C_P[4]}]
set_property PACKAGE_PIN D1 [get_ports {fmc_hpc_DP_M2C_N[4]}]
set_property PACKAGE_PIN C4 [get_ports {fmc_hpc_DP_M2C_P[5]}]
set_property PACKAGE_PIN C3 [get_ports {fmc_hpc_DP_M2C_N[5]}]
set_property PACKAGE_PIN A4 [get_ports {fmc_hpc_DP_M2C_P[6]}]
set_property PACKAGE_PIN A3 [get_ports {fmc_hpc_DP_M2C_N[6]}]
set_property PACKAGE_PIN B2 [get_ports {fmc_hpc_DP_M2C_P[7]}]
set_property PACKAGE_PIN B1 [get_ports {fmc_hpc_DP_M2C_N[7]}]

set_property PACKAGE_PIN N5 [get_ports {fmc_hpc_DP_C2M_P[0]}]
set_property PACKAGE_PIN N4 [get_ports {fmc_hpc_DP_C2M_N[0]}]
set_property PACKAGE_PIN L5 [get_ports {fmc_hpc_DP_C2M_P[1]}]
set_property PACKAGE_PIN L4 [get_ports {fmc_hpc_DP_C2M_N[1]}]
set_property PACKAGE_PIN J5 [get_ports {fmc_hpc_DP_C2M_P[2]}]
set_property PACKAGE_PIN J4 [get_ports {fmc_hpc_DP_C2M_N[2]}]
set_property PACKAGE_PIN G5 [get_ports {fmc_hpc_DP_C2M_P[3]}]
set_property PACKAGE_PIN G4 [get_ports {fmc_hpc_DP_C2M_N[3]}]
set_property PACKAGE_PIN F7 [get_ports {fmc_hpc_DP_C2M_P[4]}]
set_property PACKAGE_PIN F6 [get_ports {fmc_hpc_DP_C2M_N[4]}]
set_property PACKAGE_PIN E5 [get_ports {fmc_hpc_DP_C2M_P[5]}]
set_property PACKAGE_PIN E4 [get_ports {fmc_hpc_DP_C2M_N[5]}]
set_property PACKAGE_PIN B7 [get_ports {fmc_hpc_DP_C2M_P[6]}]
set_property PACKAGE_PIN B6 [get_ports {fmc_hpc_DP_C2M_N[6]}]
set_property PACKAGE_PIN D7 [get_ports {fmc_hpc_DP_C2M_P[7]}]
set_property PACKAGE_PIN D6 [get_ports {fmc_hpc_DP_C2M_N[7]}]

# user clocks
set_property PACKAGE_PIN W24 [get_ports {fmc_hpc_CLK_M2C_N_0}]
set_property PACKAGE_PIN V24 [get_ports {fmc_hpc_CLK_M2C_P_0}]
set_property PACKAGE_PIN AC21 [get_ports {fmc_hpc_CLK_M2C_N_1}]
set_property PACKAGE_PIN AB21 [get_ports {fmc_hpc_CLK_M2C_P_1}]

# user data LA, 00,01,17,18 are CC compatible
set_property PACKAGE_PIN U25 [get_ports fmc_hpc_LA_N_0]
set_property PACKAGE_PIN T25 [get_ports fmc_hpc_LA_P_0]
set_property PACKAGE_PIN U24 [get_ports fmc_hpc_LA_N_1]
set_property PACKAGE_PIN T24 [get_ports fmc_hpc_LA_P_1]
set_property PACKAGE_PIN P26 [get_ports fmc_hpc_LA_N_2]
set_property PACKAGE_PIN P25 [get_ports fmc_hpc_LA_P_2]
set_property PACKAGE_PIN T23 [get_ports fmc_hpc_LA_N_3]
set_property PACKAGE_PIN T22 [get_ports fmc_hpc_LA_P_3]
set_property PACKAGE_PIN V26 [get_ports fmc_hpc_LA_N_4]
set_property PACKAGE_PIN U26 [get_ports fmc_hpc_LA_P_4]
set_property PACKAGE_PIN AA18 [get_ports fmc_hpc_LA_N_5]
set_property PACKAGE_PIN Y18 [get_ports fmc_hpc_LA_P_5]
set_property PACKAGE_PIN W26 [get_ports fmc_hpc_LA_N_6]
set_property PACKAGE_PIN W25 [get_ports fmc_hpc_LA_P_6]
set_property PACKAGE_PIN AA25 [get_ports fmc_hpc_LA_N_7]
set_property PACKAGE_PIN AA24 [get_ports fmc_hpc_LA_P_7]
set_property PACKAGE_PIN W23 [get_ports fmc_hpc_LA_N_8]
set_property PACKAGE_PIN V23 [get_ports fmc_hpc_LA_P_8]
set_property PACKAGE_PIN Y26 [get_ports fmc_hpc_LA_N_9]
set_property PACKAGE_PIN Y25 [get_ports fmc_hpc_LA_P_9]
set_property PACKAGE_PIN P24 [get_ports fmc_hpc_LA_N_10]
set_property PACKAGE_PIN N24 [get_ports fmc_hpc_LA_P_10]
set_property PACKAGE_PIN AB22 [get_ports fmc_hpc_LA_N_11]
set_property PACKAGE_PIN AA22 [get_ports fmc_hpc_LA_P_11]
set_property PACKAGE_PIN Y23 [get_ports fmc_hpc_LA_N_12]
set_property PACKAGE_PIN Y22 [get_ports fmc_hpc_LA_P_12]
set_property PACKAGE_PIN AC23 [get_ports fmc_hpc_LA_N_13]
set_property PACKAGE_PIN AC22 [get_ports fmc_hpc_LA_P_13]
set_property PACKAGE_PIN AF22 [get_ports fmc_hpc_LA_N_14]
set_property PACKAGE_PIN AE22 [get_ports fmc_hpc_LA_P_14]
set_property PACKAGE_PIN AE21 [get_ports fmc_hpc_LA_N_15]
set_property PACKAGE_PIN AD21 [get_ports fmc_hpc_LA_P_15]
set_property PACKAGE_PIN AE23 [get_ports fmc_hpc_LA_N_16]
set_property PACKAGE_PIN AD23 [get_ports fmc_hpc_LA_P_16]
set_property PACKAGE_PIN AD19 [get_ports fmc_hpc_LA_N_17]
set_property PACKAGE_PIN AC19 [get_ports fmc_hpc_LA_P_17]
set_property PACKAGE_PIN AE20 [get_ports fmc_hpc_LA_N_18]
set_property PACKAGE_PIN AD20 [get_ports fmc_hpc_LA_P_18]
set_property PACKAGE_PIN AE16 [get_ports fmc_hpc_LA_N_19]
set_property PACKAGE_PIN AD16 [get_ports fmc_hpc_LA_P_19]
set_property PACKAGE_PIN AD18 [get_ports fmc_hpc_LA_N_20]
set_property PACKAGE_PIN AC18 [get_ports fmc_hpc_LA_P_20]
set_property PACKAGE_PIN AB19 [get_ports fmc_hpc_LA_N_21]
set_property PACKAGE_PIN AA19 [get_ports fmc_hpc_LA_P_21]
set_property PACKAGE_PIN AB20 [get_ports fmc_hpc_LA_N_22]
set_property PACKAGE_PIN AA20 [get_ports fmc_hpc_LA_P_22]
set_property PACKAGE_PIN AA17 [get_ports fmc_hpc_LA_N_23]
set_property PACKAGE_PIN Y17 [get_ports fmc_hpc_LA_P_23]
set_property PACKAGE_PIN AF19 [get_ports fmc_hpc_LA_N_24]
set_property PACKAGE_PIN AF18 [get_ports fmc_hpc_LA_P_24]
set_property PACKAGE_PIN AC24 [get_ports fmc_hpc_LA_N_25]
set_property PACKAGE_PIN AB24 [get_ports fmc_hpc_LA_P_25]
set_property PACKAGE_PIN Y21 [get_ports fmc_hpc_LA_N_26]
set_property PACKAGE_PIN Y20 [get_ports fmc_hpc_LA_P_26]
set_property PACKAGE_PIN AC17 [get_ports fmc_hpc_LA_N_27]
set_property PACKAGE_PIN AB17 [get_ports fmc_hpc_LA_P_27]
set_property PACKAGE_PIN AF17 [get_ports fmc_hpc_LA_N_28]
set_property PACKAGE_PIN AE17 [get_ports fmc_hpc_LA_P_28]
set_property PACKAGE_PIN AE26 [get_ports fmc_hpc_LA_N_29]
set_property PACKAGE_PIN AE25 [get_ports fmc_hpc_LA_P_29]
set_property PACKAGE_PIN AD25 [get_ports fmc_hpc_LA_N_30]
set_property PACKAGE_PIN AD24 [get_ports fmc_hpc_LA_P_30]
set_property PACKAGE_PIN AB26 [get_ports fmc_hpc_LA_N_31]
set_property PACKAGE_PIN AB25 [get_ports fmc_hpc_LA_P_31]
set_property PACKAGE_PIN AD26 [get_ports fmc_hpc_LA_N_32]
set_property PACKAGE_PIN AC26 [get_ports fmc_hpc_LA_P_32]
set_property PACKAGE_PIN AF25 [get_ports fmc_hpc_LA_N_33]
set_property PACKAGE_PIN AF24 [get_ports fmc_hpc_LA_P_33]

# I2C
set_property PACKAGE_PIN AB15 [get_ports fmc_hpc_SCL]
set_property PACKAGE_PIN AB16 [get_ports fmc_hpc_SDA]

###############################################################################
# general I/O standard constraints
###############################################################################

# user data pins are set as single-ended by default, when used as differential pairs, set them in project-specific constraints
set_property IOSTANDARD LVCMOS18 [get_ports fmc_hpc_LA_*]
