###############################################################################
# 200MHz DDR4 reference clock
###############################################################################
create_clock -period 5.000 [get_ports ddr4_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports ddr4_clk_p]

set_property PACKAGE_PIN K22 [get_ports ddr4_clk_p]
set_property PACKAGE_PIN K23 [get_ports ddr4_clk_n]
set_property IOSTANDARD DIFF_SSTL12 [get_ports ddr4_clk_n]

# DDR
set_property PACKAGE_PIN D26 [get_ports {ddr4_adr[0]}]
set_property PACKAGE_PIN D25 [get_ports {ddr4_adr[1]}]
set_property PACKAGE_PIN E26 [get_ports {ddr4_adr[2]}]
set_property PACKAGE_PIN C24 [get_ports {ddr4_adr[3]}]
set_property PACKAGE_PIN C26 [get_ports {ddr4_adr[4]}]
set_property PACKAGE_PIN F24 [get_ports {ddr4_adr[5]}]
set_property PACKAGE_PIN M26 [get_ports {ddr4_adr[6]}]
set_property PACKAGE_PIN B25 [get_ports {ddr4_adr[7]}]
set_property PACKAGE_PIN G26 [get_ports {ddr4_adr[8]}]
set_property PACKAGE_PIN B26 [get_ports {ddr4_adr[9]}]
set_property PACKAGE_PIN E25 [get_ports {ddr4_adr[10]}]
set_property PACKAGE_PIN H26 [get_ports {ddr4_adr[11]}]
set_property PACKAGE_PIN D23 [get_ports {ddr4_adr[12]}]
set_property PACKAGE_PIN F25 [get_ports {ddr4_adr[13]}]
set_property PACKAGE_PIN K25 [get_ports {ddr4_adr[14]}]
set_property PACKAGE_PIN E23 [get_ports {ddr4_adr[15]}]
set_property PACKAGE_PIN F22 [get_ports {ddr4_adr[16]}]

set_property PACKAGE_PIN M25 [get_ports {ddr4_ba[0]}]
set_property PACKAGE_PIN F23 [get_ports {ddr4_ba[1]}]
set_property PACKAGE_PIN K26 [get_ports ddr4_bg]

set_property PACKAGE_PIN D24 [get_ports ddr4_cs_n]


set_property PACKAGE_PIN L24 [get_ports ddr4_cke]
set_property PACKAGE_PIN H24 [get_ports ddr4_odt]
set_property PACKAGE_PIN J26 [get_ports ddr4_act_n]

set_property PACKAGE_PIN L25 [get_ports ddr4_reset_n]

set_property PACKAGE_PIN A22 [get_ports {ddr4_dm_n[3]}]
set_property PACKAGE_PIN C23 [get_ports {ddr4_dq[24]}]
set_property PACKAGE_PIN C22 [get_ports {ddr4_dq[25]}]
set_property PACKAGE_PIN A24 [get_ports {ddr4_dq[26]}]
set_property PACKAGE_PIN B22 [get_ports {ddr4_dq[27]}]
set_property PACKAGE_PIN A25 [get_ports {ddr4_dq[28]}]
set_property PACKAGE_PIN D21 [get_ports {ddr4_dq[29]}]
set_property PACKAGE_PIN B24 [get_ports {ddr4_dq[30]}]
set_property PACKAGE_PIN E21 [get_ports {ddr4_dq[31]}]

set_property PACKAGE_PIN H18 [get_ports {ddr4_dm_n[2]}]
set_property PACKAGE_PIN G20 [get_ports {ddr4_dq[16]}]
set_property PACKAGE_PIN D19 [get_ports {ddr4_dq[17]}]
set_property PACKAGE_PIN D20 [get_ports {ddr4_dq[18]}]
set_property PACKAGE_PIN F19 [get_ports {ddr4_dq[19]}]
set_property PACKAGE_PIN G21 [get_ports {ddr4_dq[20]}]
set_property PACKAGE_PIN E18 [get_ports {ddr4_dq[21]}]
set_property PACKAGE_PIN D18 [get_ports {ddr4_dq[22]}]
set_property PACKAGE_PIN F18 [get_ports {ddr4_dq[23]}]

set_property PACKAGE_PIN C18 [get_ports {ddr4_dm_n[1]}]
set_property PACKAGE_PIN B19 [get_ports {ddr4_dq[8]}]
set_property PACKAGE_PIN C17 [get_ports {ddr4_dq[9]}]
set_property PACKAGE_PIN B20 [get_ports {ddr4_dq[10]}]
set_property PACKAGE_PIN B15 [get_ports {ddr4_dq[11]}]
set_property PACKAGE_PIN A19 [get_ports {ddr4_dq[12]}]
set_property PACKAGE_PIN A15 [get_ports {ddr4_dq[13]}]
set_property PACKAGE_PIN A20 [get_ports {ddr4_dq[14]}]
set_property PACKAGE_PIN B17 [get_ports {ddr4_dq[15]}]

set_property PACKAGE_PIN G15 [get_ports {ddr4_dm_n[0]}]
set_property PACKAGE_PIN C16 [get_ports {ddr4_dq[0]}]
set_property PACKAGE_PIN G16 [get_ports {ddr4_dq[1]}]
set_property PACKAGE_PIN D15 [get_ports {ddr4_dq[2]}]
set_property PACKAGE_PIN G17 [get_ports {ddr4_dq[3]}]
set_property PACKAGE_PIN H17 [get_ports {ddr4_dq[4]}]
set_property PACKAGE_PIN H16 [get_ports {ddr4_dq[5]}]
set_property PACKAGE_PIN D16 [get_ports {ddr4_dq[6]}]
set_property PACKAGE_PIN E15 [get_ports {ddr4_dq[7]}]

set_property PACKAGE_PIN G24 [get_ports ddr4_ck_t]
set_property PACKAGE_PIN G25 [get_ports ddr4_ck_c]

set_property PACKAGE_PIN E16 [get_ports {ddr4_dqs_t[0]}]
set_property PACKAGE_PIN E17 [get_ports {ddr4_dqs_c[0]}]
set_property PACKAGE_PIN A17 [get_ports {ddr4_dqs_t[1]}]
set_property PACKAGE_PIN A18 [get_ports {ddr4_dqs_c[1]}]
set_property PACKAGE_PIN F20 [get_ports {ddr4_dqs_t[2]}]
set_property PACKAGE_PIN E20 [get_ports {ddr4_dqs_c[2]}]
set_property PACKAGE_PIN C21 [get_ports {ddr4_dqs_t[3]}]
set_property PACKAGE_PIN B21 [get_ports {ddr4_dqs_c[3]}]
