name: Run scala 2.13 tests

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  run-test:
    uses: ./.github/workflows/sbt-tests.yml
    with:
      scala_version: '2.13.12'
      runner_os: 'Linux'
      github_sha: ${{ github.sha }}
